spring:
  application:
    name: spring
  datasource:
    url: jdbc:postgresql://147.45.151.57:5432/itumandeev?currentSchema=animals
    username: itumandeev
    password: itumandeev
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      default_schema: animals
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml